### ISSUE TITLE
Provide an actual demo page src

### ISSUE THREAD

**Issue by aexvir** [polonel/SnackbarDemo#3]
Right now this repo contains the resources that I've downloaded directly from the browser, as I didn't have proper access to the sources. The html file contains some javascript modified attributes  and is quite messy overall.

@polonel if you have the original resources it would be nice to have them instead of this browser-parsed copy.

**Comment by polonel** [comment]
@aexvir Sorry, I'll push them up tonight.

**Comment by aexvir** [comment]
@polonel This seems closed on c70ed1f221fd940a795005f7f1d89b871623f643
