### ISSUE TITLE
Automatically reflect changes on the demo page

### ISSUE THREAD

**Issue by aexvir** [polonel/SnackbarDemo#4]
Maybe we should trigger a git pull on the server whenever changes on master are made. Right now what is on the repo is not reflected on the server, which is quite undesirable.

@polonel tell me if you are ok with this and if you can set up a GitHub trigger to have it update automatically without further actions.

Thanks!

**Comment by polonel** [comment]
@aexvir Yes, that is my plan. I'm working on getting this done. I was hoping to have it by this past weekend but got held up on another project.

**Comment by aexvir** [comment]
@polonel Don't worry :)

**Comment by polonel** [comment]
@aexvir This has been setup, it will now deploy on push to master.

**Comment by aexvir** [comment]
@polonel Awesome! Thanks
